# Generated by Django 5.2.7 on 2025-10-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option5',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option6',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
    ]
